name: Build GDS using OpenLANE and sky130 PDK

on: [push]
jobs:
  build-openlane-sky130:
    runs-on: ubuntu-latest
    env:
      REPO : qerv
      VLNV : qerv
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: qerv
      - run: echo "EDALIZE_LAUNCHER=el_docker" >> $GITHUB_ENV
      - run: pip3 install fusesoc
      - run: fusesoc library add serv https://github.com/olofk/serv
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --build-root=sky130 --target=sky130 $VLNV
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: serv.gds
          path: /home/runner/work/serv/serv/sky130/sky130-openlane/gds/serv_synth_wrapper.gds
