name: Run quick simulations

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Simulation
    env:
      REPO : qerv
      VLNV : qerv
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: qerv
      - run: sudo apt install iverilog
      - run: pip3 install fusesoc
      - run: fusesoc library add serv https://github.com/olofk/serv
      - run: fusesoc library add $REPO $GITHUB_WORKSPACE/$REPO
      - run: fusesoc run --target=sim --tool=icarus servant --timeout=1000000 --firmware serv/sw/hello_uart.hex > out.log
      - run: grep "Hi, I'm Pervant!" out.log && grep "Test complete" out.log
